### ISSUE TITLE
Error: [vite]: Rollup failed to resolve import "@hls-downloader/core/lib/store"

### ISSUE THREAD

**Issue by 0xdevalias** [puemos/hls-downloader#330]
**Describe the bug**

With tag `v4.0.1` checked out, running `./scripts/build.sh` gets the following error:

```
..snip..

> @hls-downloader/background@4.0.1 build
> vite build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.1.7 building for production...
✓ 1 modules transformed.
x Build failed in 32ms
error during build:) ⠼ reify:unist-util-visit-parents: http fetch GET 200 https://registry.npmjs.org/unist-util-visit-parents/-/unist-util-visit-parents-6.0.1
Error: [vite]: Rollup failed to resolve import "@hls-downloader/core/lib/store" from "/Users/devalias/dev/hls-downloader/src/background/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:67195:27)
    at onRollupWarning (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:67223:9)
    at onwarn (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:66927:13)
    at file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:17398:13
    at Object.logger [as onLog] (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:19056:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:18002:26)
    at file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:17960:26

..snip..
```

**To Reproduce**
1. `git fetch`
2. git checkout v4.0.1
3. `./scripts/build.sh`

**Expected behavior**
Everything would build properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Browser: N/A
 - Node Version: v20.2.0

**Additional context**
N/A

**Comment by 0xdevalias** [comment]
Apparently it can be triggered more specifically with `./scripts/build-background.sh`:

```
⇒ scripts/build-background.sh

up to date, audited 54 packages in 617ms

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> @hls-downloader/background@4.0.1 build
> vite build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.1.7 building for production...
✓ 1 modules transformed.
x Build failed in 33ms
error during build:
Error: [vite]: Rollup failed to resolve import "@hls-downloader/core/lib/store" from "/Users/devalias/dev/hls-downloader/src/background/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:67195:27)
    at onRollupWarning (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:67223:9)
    at onwarn (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:66927:13)
    at file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:17398:13
    at Object.logger [as onLog] (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:19056:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:18002:26)
    at file:///Users/devalias/dev/hls-downloader/src/background/node_modules/rollup/dist/es/shared/node-entry.js:17960:26
```

**Comment by puemos** [comment]
Thanks! it's been fixed

**Comment by 0xdevalias** [comment]
Commit for future reference: https://github.com/puemos/hls-downloader/commit/5c415bca50e771424b6575a392ecc6fc5c84771b
